name = "Will Stubbs"
description = "Doing my best."
keywords = ""
image = "profile-cropped.jpg"
theme = "dark"
#primary_color = "#d81b60"
primary_color = "#396c91"
text_align = "center"
gtag_id = ""
base_url = "https://wastubbs.github.io/contact/"

[[sections]]
title = "Contact"
description = "Where to find me"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/signal/3B45FD"
title = "Signal"
url = "https://signal.me/#eu/0lg0xfBrgcCqjU4j-H_3sMXIYrv7TlGzF7rbDJY8L1fFhHukhDxOVIYo3zB3caXB"
[[sections.items]]
icon = "https://cdn.simpleicons.org/telegram/26A5E4"
title = "Telegram"
url = "https://t.me/porktenderloin"
[[sections.items]]
title = "Email"
icon = "https://cdn.simpleicons.org/Gmail/EA4335"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
[[sections.items]]
title = "Spotify"
icon = "https://cdn.simpleicons.org/spotify/1ED760"
url = "https://open.spotify.com/user/bokb0vp0muh7gnuuvg3cxxlnk?si=8f1f62117260493e"
[[sections.items]]
title = "Snap"
icon = "https://cdn.simpleicons.org/snapchat/FFFC00"
url = "https://www.snapchat.com/add/will3129"
[[sections.items]]
title = "Discord"
icon = "https://cdn.simpleicons.org/discord/5865F2"
url = "https://discord.com/users/657793002886135829"
