name = "Will Stubbs"
description = "Doing my best."
keywords = ""
image = "profile-cropped.jpg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://wastubbs.github.io/contact/"

[[sections]]
title = "Contact"
description = "Where to find me"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/signal/ffffff"
title = "Signal"
url = "https://signal.me/#eu/0lg0xfBrgcCqjU4j-H_3sMXIYrv7TlGzF7rbDJY8L1fFhHukhDxOVIYo3zB3caXB"
[[sections.items]]
icon = "https://cdn.simpleicons.org/telegram/ffffff"
title = "Telegram"
url = "https://www.imdb.com/name/nm0350453/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/sms/ffffff"
title = "SMS"
url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
[[sections.items]]
title = "Email"
icon = "https://cdn.simpleicons.org/email/ffffff"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
[[sections.items]]
title = "Spotify"
icon = "https://cdn.simpleicons.org/spotify/ffffff"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
[[sections.items]]
title = "Snap"
icon = "https://cdn.simpleicons.org/snapchat/ffffff"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
