name = "Will Stubbs"
description = "Doing my best."
keywords = ""
image = "profile-cropped.jpg"
theme = "dark"
#primary_color = "#d81b60"
primary_color = "#396c91"
text_align = "center"
gtag_id = ""
base_url = "https://wastubbs.github.io/contact/"

[[sections]]
title = "Huh?"
description = "I'm shutting down my Meta accounts, and encourage you to do the same!"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "What about poker?"
embed_url = "https://docs.google.com/forms/d/e/1FAIpQLSemPjKnBI_KIxt4J_FquldDnl5XIJzNB56bfBQuqsBzLxbNhg/viewform?embedded=true"
[[sections.items]]
title = "Why Signal?"
description = "Here's a quick-start guide that talks about the primary benefits to Signal over oligarch-owned options."
url = "https://freedom.press/digisec/blog/signal-beginners/"
[[sections.items]]
title = "What about cute pics of your kids???"
description = "It's coming! Using ATProto, a platform-agnostic communications protocol started by the Bluesky team, we will soon have apps that look & feel like Instagram, called Flashes"
url = "https://bsky.app/profile/flashesapp.bsky.social"
[[sections.items]]
title = "What about my brain rot?"
description = "The same person working on Flashes is also cooking up a short videos app called Bluescreen!"
url = "https://bsky.app/profile/bluescreen.blue"


[[sections]]
title = "Contact"
description = "Where to find me"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/signal/3B45FD"
title = "Signal"
url = "https://signal.me/#eu/0lg0xfBrgcCqjU4j-H_3sMXIYrv7TlGzF7rbDJY8L1fFhHukhDxOVIYo3zB3caXB"
[[sections.items]]
icon = "https://cdn.simpleicons.org/telegram/26A5E4"
title = "Telegram"
url = "https://t.me/porktenderloin"
[[sections.items]]
title = "Email"
icon = "https://cdn.simpleicons.org/Gmail/EA4335"
url = "mailto:wastubbs@gmail.com"
[[sections.items]]
title = "Spotify"
icon = "https://cdn.simpleicons.org/spotify/1ED760"
url = "https://open.spotify.com/user/bokb0vp0muh7gnuuvg3cxxlnk?si=8f1f62117260493e"
[[sections.items]]
title = "Snap"
icon = "https://cdn.simpleicons.org/snapchat/FFFC00"
url = "https://www.snapchat.com/add/will3129"
[[sections.items]]
title = "Discord"
icon = "https://cdn.simpleicons.org/discord/5865F2"
url = "https://discord.com/users/657793002886135829"
[[sections.items]]
title = "Bluesky"
icon = "https://cdn.simpleicons.org/bluesky/0285FF"
url = "https://bsky.app/profile/wbbaggins.bsky.social"
